### ISSUE TITLE
Chat Icon and Chat window both aren't clickable but showing on page in Angular 5

### ISSUE THREAD

**Issue by saqibtalib** [livechat/angular-livechat#10]
Hi Support,

I've a query regarding chat integration with Angular 5. I've purchased a plan and according to your given live-Chat angular documentation I integrated it with my app. I've followed stack blitz for more detail but in my case when page loads first time the icon shows with tool tip box **'how can I help you'**  this box is clickable and once I click the box chat window become open which is not clickable anymore. Everything is working fine on site behind the chat box but chat box stuck there.

Please let me know what is the issue. You can check it by going here http://dev.hayaat.pk

Thank you.

Code:

app.module.ts

import { LivechatWidgetModule } from '@livechat/angular-widget';
@NgModule({
  imports: [
    LivechatWidgetModule,
]
})
--------------------------------------

app.component.ts

export class AppComponent {
  licenseId:number = 0000000;
}

---------------------------------------
app.component.html.ts

<livechat-widget [licenseId]="licenseId"></livechat-widget>

**Comment by ZiggyKraus** [comment]
Hello @saqibtalib,

I have checked your implementation, and I was able to found the issue. The problem is caused by the CSS snippet that you are using on your website, and that is influencing all iframe on your page (including our LiveChat).

Here's the CSS that I'm talking about:

```
iframe {
    width: 100%;
    display: block;
    pointer-events: none;
    position: relative /* IE needs a position other than static */;
}
```
you can find it here: http://dev.hayaat.pk/styles.dac8cf53d12649c221c4.bundle.css. If you will remove the `pointer-events: none;` entry from it, chat widget will start working properly :)

@saqibtalib, I hope that I was able to help, but in case of any additional questions, please don't hesitate to ask.
