### ISSUE TITLE
Please level up the peer dependency options

### ISSUE THREAD

**Issue by stevefarwell** [livechat/angular-livechat#25]
add 7, 8 (9 is due to drop soon)

@livechat/angular-widget@0.1.0 requires a peer of @angular/core@^2.4.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
@livechat/angular-widget@0.1.0 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.

**Comment by romelgomez** [comment]
This project set a strict peerDependencies on @angular/core lib and not make use of nothing fancy that will hard change on the future, please remove this check because it's a common request here, and there are not maintainer that keep update this plugin. The same for rxjs. 

https://github.com/livechat/angular-livechat/blob/master/package.json#L21

`import { Component, Input, Output, NgModule } from '@angular/core';`

`"@angular/core": "^2.4.0 || ^4.0.0 || ^5.0.0 || ^6.0.0",`

**Comment by mreszke** [comment]
@stevefarwell problem has been resolved in a new version of the package

**Comment by romelgomez** [comment]
@mreszke  Thanks this change resolve this Issue. 

Note: This will again raise in the future other issue. 

Removing peerDependencies declaration resolve the issue permanently.

https://nodejs.org/es/blog/npm/peer-dependencies/

"I only work when plugged in to version 1.2.x of my host package, so if you install me, be sure that it's alongside a compatible host." We call this relationship a peer dependency.

Meaning that only theses version has the methods that need to correctly run the plugin.  And this plugin use core not experimental stuff that are old as the v2 of angular.

**Comment by mreszke** [comment]
In our opinion, it's still better to test it with a new version of angular and then release with updated peerDependency. You never know what will be changed

**Comment by romelgomez** [comment]
@mreszke Cool, thanks for update the project.  Please @stevefarwell close the issue, it's already fixed.
